# Site settings
title: yangbo's Personal Website
email: 467198215@qq.com
description: yangbo's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: yangbo1
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/yangbo1/blog/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/yangbo1/yangbo1.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: yangbo1
#duoshuo_url: "http://yangbo1.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: yangbo1
disqus_url: "http://yangbo1.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
